name: clean_architecture_flutter
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Service locator
  get_it: ^7.2.0
  # Provider for state management
  provider: ^6.0.4
  flutter_bloc: ^8.1.1
  freezed: ^2.3.0
  # Value equality
  equatable: ^2.0.5
  # Functional programming thingies
  dartz: ^0.10.1
  # Remote API
  connectivity_plus: ^3.0.2
  http: ^0.13.5
  # Local cache
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/